### ISSUE TITLE
Erratic scroll behavior on iOS Safari when the cursor is in treecorder text box

### ISSUE THREAD

**Issue by jwalgran** [azavea/nyc-trees#1665] opened 2015-05-14 21:39 UTC
In the treecorder on Mobile Safari, scrolling while focused on a text field results in the cursor "floating" outside the text box.

http://cl.ly/2X2g0v2d3X0H/erratic-ios-scrolling-on-treecorder.mov

This does not happen all forms.

http://cl.ly/213c231T3x2s/ios-scrolling-on-event-form.mov

**Comment by jfrankl** [comment] 2015-05-15 14:18
@jwalgran Could you provide iOS and iPhone version information? I can't reproduce this on the office iPhone 4 + iOS7.

**Comment by jwalgran** [comment] 2015-05-15 14:23
It happens on my real 4s with the latest iOS (8.3 I think) as well as the
simulator 4s and 5s

**Comment by jfrankl** [comment] 2015-05-15 19:36
Working on the fix with @RickMohr. Here is the current status: 87d34b6914648e97adc5de741c3046a6b4726430

I was able to fix the glitchy scrolling with keyboard open, but it broke the fixed "Tree 1" elements. Rick is working on getting that to work again.

**Comment by RickMohr** [comment] 2015-05-18 13:48
Should be fixed by https://github.com/RickMohr/nyc-trees/tree/fix-sticky-titles

**Comment by jfrankl** [comment] 2015-05-18 16:45
Fixed by #1685.

**Closed by jfrankl** 2015-05-18 16:45 UTC
Labels: design, in review
