### ISSUE TITLE
Users still have a blockface reserved after mapping if the block is later marked as available

### ISSUE THREAD

**Issue by maurizi** [azavea/nyc-trees#1573] opened 2015-05-06 20:16 UTC
Scenario 1:
1. A user reserves a blockface, maps it, and then chooses "I'm done for now"
2. Later after QA/QC a census admin determines that the block should be remapped, and marks it as available
3. It is now shown as reserved by the user who originally mapped it.  Since they may have made additional reservations in the mean time, this can push that user over the 12 blockface reservation limit.

Scenario 2:
1. A user reserves a blockface, maps it, and then chooses "No, restart"
2. It is still reserved by that user, and they can remap it immediately.

Scenario 2 seems correct, but scenario 1 does not.  I propose that when surveying a blockface *as an individual mapper*, when a user completes a survey we mark their `BlockfaceReservation` as "expired".  If they then choose "No, restart", we should give them a new reservation.

**Comment by kdeloach** [comment] 2015-05-06 22:02
Alternatively, if the user selects "Yes" on the "Does this look right?" question, we could mark the reservation as expired then.

**Comment by steventlamb** [comment] 2015-05-11 14:38
We've gone back and forth about what should and shouldn't happen on the survey confirmation page, and it was decided, against what would be intuitive, to make the 'yes' button on the confirmation page essentially do nothing and treat the confirmation page as merely an opportunity to flag. This is confusing as it is, and modifying it slightly to mark the reservation as expired but *not* modify the availability of the blockface could make it more-so because these data points should ideally be connected.

The former solution has the advantage of being simpler, the latter is easier.

**Comment by dboyer** [comment] 2015-05-11 14:40
To confirm, @maurizi 's first scenario is definitely incorrect. If a census admin marks a block as available again, it should not be reserved for anyone. The expected use case is that Parks will mark it as available based on QA/QC and then reserve it for a Parks mapper to complete.

**Comment by kdeloach** [comment] 2015-05-11 14:50
We discovered another issue (regression?). If the user quits the survey for any reason "I cannot map this block because..." the block remains reserved by that user. Whatever solution we implement for this issue should also address this scenario as well.

**Comment by dboyer** [comment] 2015-05-11 15:00
I believe that the block should not be made available again or marked as reserved by that user if they select "I cannot map this block because..." The use case is blocks that are under construction, have hazards, or are otherwise inaccessible. Parks will check the data for a quit reason and make the block available again if necessary. I can confirm that though.

**Comment by steventlamb** [comment] 2015-05-11 20:19
@dboyer @kdeloach please see the `PROPOSAL` commit linked immediately above this message.

**Comment by dboyer** [comment] 2015-05-11 20:49
I emailed Parks about this but have not heard back yet.

**Comment by steventlamb** [comment] 2015-05-11 20:52
got it, I will hold. Please note the text change - I am proposing we change 'I cannot' to 'This <..> cannot' in order to hint that the purpose of the button is to indicate objective obstructions like construction rather than personal ones like running out of time.

**Comment by dboyer** [comment] 2015-05-13 19:22
Parks has confirmed that if a user selects "I cannot map this block because...." the block should be marked as completed and not made available for another user or remain reserved for that user. 

Let's not change the text for now. The "I cannot map this block because..." help text mentions offset beds and I think people actually can map those so I want to check on the text in general.

**Closed** 2015-05-14 21:54 UTC
Labels: launch
