### ISSUE TITLE
Reservations page: in "mobile view", action popup not visible

### ISSUE THREAD

**Issue by RickMohr** [azavea/nyc-trees#570] opened 2015-02-16 20:17 UTC
1) Go to the reservations page and make sure you have some reservations.
2) Select one and click the blue button in the action bar.

You can see the popup's shadow at the bottom of the map, but not its content:

![image](https://cloud.githubusercontent.com/assets/2162993/6218674/b87ad846-b5ee-11e4-8ef8-985a5fd93984.png)

**Comment by maurizi** [comment] 2015-02-16 20:28
Duplicate of #413

**Closed by maurizi** 2015-02-16 20:28 UTC
