### ISSUE TITLE
When mapping at an event you are allowed to map "unavailable" blocks

### ISSUE THREAD

**Issue by RickMohr** [azavea/nyc-trees#1463] opened 2015-04-27 20:38 UTC
1) Make an event going on right now (I just make it last for a month)
2) RSVP to the event and map a block
3) Continue mapping. The block you just mapped is now gray (unavailable) but you can still select and map it.

**Comment by steventlamb** [comment] 2015-05-11 20:46
Could not reproduce. Fixed by the crosshairs or something similar.

**Closed** 2015-05-21 17:11 UTC
Labels: launch
