### ISSUE TITLE
500 error on long blocks

### ISSUE THREAD

**Issue by dboyer** [azavea/nyc-trees#1418] opened 2015-04-23 16:43 UTC
From Parks:

We are getting a 500 Forbidden Error after submitting surveys, on for long blocks, but not short blocks.  Instead of getting the tree points with the satellite overlay, we are getting the 500 Forbidden Error instead.  However, checking the Django backend, it appears that surveys are actually submitted / data is captured.  

Maybe related to #838 ?

**Comment by maurizi** [comment] 2015-04-23 16:45
That definitely sounds related to #838

**Comment by kdeloach** [comment] 2015-05-01 21:06
Verified that this is a duplicate of #838. Here's the stack trace I got when submitting a survey where the tree distance exceeded the block length.

    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
        response = wrapped_callback(request, *callback_args, **callback_kwargs)
      File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
        return view_func(request, *args, **kwargs)
      File "/opt/app/apps/core/decorators.py", line 32, in wrapper
        return view_fn(request, *args, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/django_tinsel/decorators.py", line 33, in routed
        return req_method(request, *args2, **kwargs2)
      File "/usr/local/lib/python2.7/dist-packages/django_tinsel/decorators.py", line 79, in wrapper
        params = callable_or_dict(request, *args, **wrapper_kwargs)
      File "/opt/app/apps/core/decorators.py", line 102, in inner
        ctx = view_fn(request, *args, **kwargs)
      File "/opt/app/apps/core/decorators.py", line 102, in inner
        ctx = view_fn(request, *args, **kwargs)
      File "/opt/app/apps/survey/views.py", line 667, in survey_detail_from_event
        return _survey_detail(request, survey_id)
      File "/opt/app/apps/survey/views.py", line 655, in _survey_detail
        cursor.execute(_SURVEY_DETAIL_QUERY, [survey_id])
      File "/usr/local/lib/python2.7/dist-packages/debug_toolbar/panels/sql/tracking.py", line 174, in execute
        return self._record(self.cursor.execute, sql, params)
      File "/usr/local/lib/python2.7/dist-packages/debug_toolbar/panels/sql/tracking.py", line 104, in _record
        return method(sql, params)
      File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 81, in execute
        return super(CursorDebugWrapper, self).execute(sql, params)
      File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 65, in execute
        return self.cursor.execute(sql, params)
      File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 94, in __exit__
        six.reraise(dj_exc_type, dj_exc_value, traceback)
      File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 65, in execute
        return self.cursor.execute(sql, params)
    InternalError: line_interpolate_point: 2nd arg isnt within [0,1]
    CONTEXT:  SQL function "st_line_interpolate_point" statement 2
    PL/pgSQL function layoutboxes(geometry,boolean,double precision[],double precision[],double precision[],double precision[]) line 46 at assignment
    SQL function "layoutboxes" statement 1

**Comment by kdeloach** [comment] 2015-05-01 21:06
Duplicate of #838.

**Closed by kdeloach** 2015-05-01 21:06 UTC
Labels: queue, Treecorder testing
