### ISSUE TITLE
Group progress: name not shown for the first group clicked on

### ISSUE THREAD

**Issue by RickMohr** [azavea/nyc-trees#1702] opened 2015-05-20 13:42 UTC
1) Go to progress page, "Groups" view
2) Click on a group polygon

The group name appears briefly in the legend area but then disappears.
Clicking on subsequent groups works fine.

**Comment by jwalgran** [comment] 2015-05-20 13:44
Duplicate of #1697

**Closed by jwalgran** 2015-05-20 13:44 UTC
