### ISSUE TITLE
No option to re-enter survey tool if exit it when mapping as part of an event

### ISSUE THREAD

**Issue by dboyer** [azavea/nyc-trees#946] opened 2015-03-25 19:04 UTC
From Parks testing:

apparently if you leave the treecorder after you start mapping during an event, it can require a new RSVP / Check-in cycle to resume mapping, or at least the path to resuming mapping isn’t clear.

**Comment by jfrankl** [comment] 2015-03-27 19:38
The latest wireframes show this. I will need developers to implement.

![image](https://cloud.githubusercontent.com/assets/1809908/6875689/384450c2-d497-11e4-895a-d7503ca1955c.png)

![image](https://cloud.githubusercontent.com/assets/1809908/6875696/42616ed2-d497-11e4-8c16-ebe9b7289374.png)

**Comment by kdeloach** [comment] 2015-04-23 20:54
Duplicate of #1358

**Closed by kdeloach** 2015-04-23 20:54 UTC
Labels: Treecorder testing
