### ISSUE TITLE
Training page sidebar text does not match content

### ISSUE THREAD

**Issue by maurizi** [azavea/nyc-trees#576] opened 2015-02-16 20:56 UTC
When all online training is complete, the main content show "Training Complete", but the sidebar indicates there is more training to be done
![almost_there](https://cloud.githubusercontent.com/assets/4432106/6219191/52580fce-b5f4-11e4-993f-cfbe2c19e82f.png)

**Comment by dboyer** [comment] 2015-02-16 21:40
Let's leave this for now as we're waiting on text from Parks and TreeKIT.

**Comment by jfrankl** [comment] 2015-04-01 17:14
Will need a developer to write conditional statements to show correct text based on conditions.

**Comment by steventlamb** [comment] 2015-04-13 18:47
Changing back to design due to #1143

**Comment by steventlamb** [comment] 2015-04-13 20:29
Assigning to @dboyer because we're just waiting on content.

**Comment by dboyer** [comment] 2015-04-15 17:26
Is this a duplicate of #443 ?

**Closed** 2015-05-07 20:26 UTC
Labels: blocked
