### ISSUE TITLE
Update "Learn More" link on reservations instructions page

### ISSUE THREAD

**Issue by kdeloach** [azavea/nyc-trees#1304] opened 2015-04-21 14:01 UTC
Where does this link go?

![image](https://cloud.githubusercontent.com/assets/43062/7253842/4bb9d2c4-e80d-11e4-93b8-33ec4ca6f652.png)

**Comment by dboyer** [comment] 2015-04-21 15:59
Excellent question. I believe there was going to be a modal or page showing info on what it means to be an individual mapper. I'll check with Parks.

**Comment by maurizi** [comment] 2015-04-23 17:12
Duplicate of #1039

**Closed by maurizi** 2015-04-23 17:12 UTC
